app:
  appname: "livefun" # Change to "develop" to skip authentication for development mode
  env: "develop"
  addr: 8888
  db-type: "mysql"
  oss-type: "local"
  need-init-data: true
  UseMultipoint: false

zap:
  level: "info"
  format: "console"
  prefix: "[LIVEFUN]"
  director: "log"
  link-name: "latest_log"
  show-line: true
  encode-level: "LowercaseColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true

# mysql connect configuration
mysql:
  path: "47.104.92.151:3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "liveFun"
  username: "root"
  password: "lnmp.org#25812"
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

# jwt configuration
jwt:
  signing-key: "live-fun"

# redis configuration
redis:
  db: 0
  addr: "127.0.0.1:6379"
  password: ""
