definitions:
  model.User:
    properties:
      createdAt:
        type: string
      headerImg:
        type: string
      id:
        type: integer
      isvalid:
        type: integer
      nickName:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
      userName:
        type: string
    type: object
info:
  contact: {}
paths:
  /base/login:
    post:
      parameters:
      - description: 用户登录接口
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
swagger: "2.0"
